### ISSUE TITLE
I couldn't get a gas report for each function at unit test

### ISSUE THREAD

**Issue by 0xrpter** [0x00dev/MasterChef#1]

**Comment by 0x0geek** [comment]
First, you have to install hardhat-gas-reporter by this command
npm install hardhat-gas-reporter --save-dev

Then import this module in hardhat-config.ts
import "hardhat-gas-reporter";

Then add this to your config object
gasReporter: { currency: 'CHF', gasPrice: 21, outputFile: 'gas-report.txt', noColors: true, onlyCalledMethods: true }
